const initialState = {
    JobData : [
    {
        applicationDeadline: "2023-07-20",
        benifitAndPerks: "Not to say more about it but you will love to work with them",
        companyCulture: "Not to say more about it but you will love to work with them",
        companyName: "Facebook",
        companyWebsite: "https://www.cricbuzz.com/",
        contactEmail: "Shirin@gmail.com",
        contactPerson: "Shirin",
        contactPhoneNumber: "9801500214",
        employmentType: "Full Time",
        expectedStartDate: "2023-08-05",
        experienceLevel: "6 months",
        interviewSchedule: "2023-07-22",
        jobDescription: "You have to maintain the frontend of the web page",
        jobTitle: "SDE 1",
        oppertunityForGrowth: "Not to say more about it but you will love to work with them",
        qualification: "B Tech",
        registrationLink: "https://careers.walmart.com/us/jobs/WD1578565-senior-software-engineer",
        salary: "84.4 lakh",
        id:null,
        uid:null,
        
    },
    // {
    //     applicationDeadline: "2023-07-20",
    //     benifitAndPerks: "Not to say more about it but you will love to work with them",
    //     companyCulture: "Not to say more about it but you will love to work with them",
    //     companyName: "Google",
    //     companyWebsite: "https://www.cricbuzz.com/",
    //     contactEmail: "Shirin@gmail.com",
    //     contactPerson: "Shirin",
    //     contactPhoneNumber: "9801500214",
    //     employmentType: "Full Time",
    //     expectedStartDate: "2023-08-05",
    //     experienceLevel: "1 year",
    //     interviewSchedule: "2023-07-22",
    //     jobDescription: "You have to maintain the frontend of the web page",
    //     jobTitle: "SDE 1",
    //     oppertunityForGrowth: "Not to say more about it but you will love to work with them",
    //     qualification: "B Tech",
    //     registrationLink: "https://careers.walmart.com/us/jobs/WD1578565-senior-software-engineer",
    //     salary: "84.4 lakh",
    // },
    // {
    //     applicationDeadline: "2023-07-20",
    //     benifitAndPerks: "Not to say more about it but you will love to work with them",
    //     companyCulture: "Not to say more about it but you will love to work with them",
    //     companyName: "TCS",
    //     companyWebsite: "https://www.cricbuzz.com/",
    //     contactEmail: "Shirin@gmail.com",
    //     contactPerson: "Shirin",
    //     contactPhoneNumber: "9801500214",
    //     employmentType: "Full Time",
    //     expectedStartDate: "2023-08-05",
    //     experienceLevel: "1 year",
    //     interviewSchedule: "2023-07-22",
    //     jobDescription: "You have to maintain the frontend of the web page",
    //     jobTitle: "SDE 1",
    //     oppertunityForGrowth: "Not to say more about it but you will love to work with them",
    //     qualification: "B Tech",
    //     registrationLink: "https://careers.walmart.com/us/jobs/WD1578565-senior-software-engineer",
    //     salary: "84.4 lakh",
    // },
    // Add more job data objects here...
]
}
export default initialState;
